name: Deploy to GitHub Pages

on:
  push:
    branches: ['main'] # Ak sa tvoja vetva volá 'master', zmeň to tu na 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repozitára
        uses: actions/checkout@v4

      - name: Nastavenie Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Inštalácia závislostí
        run: npm install

      - name: Build projektu
        run: npm run build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact (zložka dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy na GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4